/**
 * Session actions
 */
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

/**
 * Survey actions
 */
export const SURVEYS_REQUEST = 'SURVEYS_REQUEST';
export const SURVEYS_REQUEST_SUCCESS = 'SURVEYS_REQUEST_SUCCESS';
export const SURVEYS_REQUEST_FAILURE = 'SURVEYS_REQUEST_FAILURE';
export const ADD_SURVEY_REQUEST = 'ADD_SURVEY_REQUEST';
export const ADD_SURVEY_SUCCESS = 'ADD_SURVEY_SUCCESS';
export const ADD_SURVEY_FAILURE = 'ADD_SURVEY_FAILURE';
export const SUBMIT_RESPONSE_REQUEST = 'SUBMIT_RESPONSE_REQUEST';
export const SUBMIT_RESPONSE_SUCCESS = 'SUBMIT_RESPONSE_SUCCESS';
export const SUBMIT_RESPONSE_FAILURE = 'SUBMIT_RESPONSE_FAILURE';
